name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run Ruff linter
      run: |
        uv run ruff check src/

    - name: Run Ruff formatter check
      run: |
        uv run ruff format --check src/

    - name: Run mypy type checker
      run: |
        uv run mypy src/

    - name: Run pyright type checker
      run: |
        uv run pyright src/

    - name: Smoke test - verify application loads
      run: |
        uv run python src/run.py --help